### ISSUE TITLE
не видит стопок при прокачке, калибровке помпы. (буду первым))

### ISSUE THREAD

**Issue by ACKET2009** [Roman-RV78/Nalivator#1]
при калибровке помпы все рюмки на местах, но говорит нет рюмок. и при промывке... Уровень датчиков стоит 0

в остальных местах стопки видит, и наливает...

хотя при повторном включении устройства промывка сработала, но потом перешёл на калибровку помпы, рюмку не убирал, соответственно обругалось на это, затем снял и обратно поставил - всё равно, говорит, нет рюмок. затем перевключил устройство, сразу пошёл в калибровку помпы, поставил пустую рюмку - пошла работать помпа.Переставил в другое место - работает. как только повторилась ситуация с отсутствием рюмки, дальше она повторяется независимо от снятия стопок... в скетче версии 3.4 и 3.3 В 3.2 нормально отрабатывает

**Comment by Roman-RV78** [comment]
Доброго. Я уже перезалил скетч, исправилОтправлено с моего устройства Huawei-------- Исходное сообщение --------Тема: [Roman-RV78/Nalivator] не видит стопок при прокачке, калибровке помпы. (буду первым)) (#1)От: ACKET2009 Кому: Roman-RV78/Nalivator Копия: Subscribed 
при калибровке помпы все рюмки на местах, но говорит нет рюмок. и при промывке... Уровень датчиков стоит 0
в остальных местах стопки видит, и наливает...
хотя при повторном включении устройства промывка сработала, но потом перешёл на калибровку помпы, рюмку не убирал, соответственно обругалось на это, затем снял и обратно поставил - всё равно, говорит, нет рюмок. затем перевключил устройство, сразу пошёл в калибровку помпы, поставил пустую рюмку - пошла работать помпа.Переставил в другое место - работает. как только повторилась ситуация с отсутствием рюмки, дальше она повторяется независимо от снятия стопок... в скетче версии 3.4 и 3.3 В 3.2 нормально отрабатывает

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Roman-RV78/Nalivator/issues/1",
"url": "https://github.com/Roman-RV78/Nalivator/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
